#!/usr/bin/env bash
# pywal hook: compute lighter/darker variants and export as extra XRDB keys.

set -euo pipefail

JSON="${HOME}/.cache/wal/colors.json"
#!/usr/bin/env bash
set -euo pipefail

python3 - <<'PY'
import json, os

json_path = os.path.expanduser("~/.cache/wal/colors.json")
xrdb_out  = os.path.expanduser("~/.cache/wal/extras.Xresources")
css_out   = os.path.expanduser("~/.cache/wal/colors-waybar-extra.css")

with open(json_path) as f:
    data = json.load(f)

def hex_to_rgb(h): return tuple(int(h[i:i+2], 16) for i in (0,2,4))
def rgb_to_hex(rgb): return "#{:02X}{:02X}{:02X}".format(*rgb)
def lighten(rgb, pct): return tuple(min(255, round(c + (255-c)*pct)) for c in rgb)
def darken(rgb, pct):  return tuple(max(0, round(c*(1-pct))) for c in rgb)

bg_hex = data["special"]["background"].lstrip("#")
c7_hex = data["colors"]["color7"].lstrip("#")

bg_rgb = hex_to_rgb(bg_hex)
c7_rgb = hex_to_rgb(c7_hex)

# tweak amounts as you like
lighter_bg_1 = rgb_to_hex(lighten(bg_rgb, 0.06))
lighter_bg_2 = rgb_to_hex(lighten(bg_rgb, 0.20))
darker_bg_1  = rgb_to_hex(darken(bg_rgb, 0.10))

c7_light_1 = rgb_to_hex(lighten(c7_rgb, 0.12))
c7_light_2 = rgb_to_hex(lighten(c7_rgb, 0.25))
c7_light_3 = rgb_to_hex(lighten(c7_rgb, 0.50))
c7_dark_1  = rgb_to_hex(darken(c7_rgb, 0.12))

# Xresources (optional, if you still want these)
with open(xrdb_out, "w") as f:
    f.write("! Auto-generated by pywal hook: bg + color7 variants\n")
    for k, v in {
        "*.lighterbg":  lighter_bg_1,
        "*.lighterbg2": lighter_bg_2,
        "*.darkerbg":   darker_bg_1,
        "*.color7_light":  c7_light_1,
        "*.color7_light2": c7_light_2,
        "*.color7_dark":   c7_dark_1,
    }.items():
        f.write(f"{k}: {v}\n")

# Waybar extra CSS variables
with open(css_out, "w") as f:
    f.write("/* Auto-generated by pywal hook */\n")
    f.write(f"@define-color lighterbg  {lighter_bg_1};\n")
    f.write(f"@define-color lighterbg2 {lighter_bg_2};\n")
    f.write(f"@define-color darkerbg   {darker_bg_1};\n")
    f.write(f"@define-color color7_light  {c7_light_1};\n")
    f.write(f"@define-color color7_light2 {c7_light_2};\n")
    f.write(f"@define-color color7_light2 {c7_light_3};\n")
    f.write(f"@define-color color7_dark   {c7_dark_1};\n")
PY

# merge Xresources (optional)
xrdb -merge ~/.cache/wal/extras.Xresources 2>/dev/null || true
